name: vpn_api
description: OpenAPI API client
version: 1.0.46+26

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dio: '^5.2.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: 2.4.12
  json_serializable: 6.8.0
  test: ^1.16.0

